import Link from "next/link";
import { ArrowRight, TrendingUp, Calendar } from "lucide-react";
import { getSiteContentByPageKey, getTrendingPosts, getAllPosts } from "@/lib/action";
import { PostCard } from "@/components/pages/blog/PostCard";
import { PostType } from "@/types";

interface TrendingArticle {
  id: number | string;
  slug: string;
  title: string;
  timeAgo: string;
}

function getTimeAgo(dateStr: string | null | undefined): string {
  if (!dateStr) return "";
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);
  if (diffMins < 1) return "just now";
  if (diffMins < 60) return `${diffMins} minute${diffMins !== 1 ? "s" : ""} ago`;
  if (diffHours < 24) return `${diffHours} hour${diffHours !== 1 ? "s" : ""} ago`;
  if (diffDays < 7) return `${diffDays} day${diffDays !== 1 ? "s" : ""} ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} week${Math.floor(diffDays / 7) !== 1 ? "s" : ""} ago`;
  return date.toLocaleDateString();
}

function formatReadTime(readTime: number | null | undefined): string {
  if (readTime == null) return "";
  return `${readTime} min read`;
}

const defaultTrendingArticles: TrendingArticle[] = [
  { id: "1", slug: "1", title: "Google released Gemini 1.0 Pro with 1M token context window", timeAgo: "2 hours ago" },
  { id: "2", slug: "2", title: "Mistral AI announces partnership with Microsoft Azure", timeAgo: "5 hours ago" },
  { id: "3", slug: "3", title: "Regulatory talks in EU finalize the new AI Act draft", timeAgo: "1 day ago" },
  { id: "4", slug: "4", title: "OpenAI releases GPT-4 Turbo with improved reasoning", timeAgo: "2 days ago" },
  { id: "5", slug: "5", title: "Anthropic introduces Claude 3.5 Sonnet with enhanced capabilities", timeAgo: "3 days ago" },
];

export default async function Latest() {
  // Fetch CMS content and latest posts from server
  const [siteContent, allPostsData, { posts: trendingPosts }] = await Promise.all([
    getSiteContentByPageKey("home"),
    getAllPosts(1, "published"),
    getTrendingPosts(5),
  ]);
  const contents = siteContent?.contents || [];
  const latestPosts = (allPostsData?.posts || []) as PostType[];

  const latestContent = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "latest");
  const digestContent = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "digest");
  const trendingContent = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "trending");
  const adContent = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "ad");
  const ad2Content = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "ad-2");
  const ad3Content = contents.find((item: { section_key: string; content?: Record<string, string> }) => item.section_key === "ad-3");
  const trendingArticles: TrendingArticle[] =
    trendingPosts?.length > 0
      ? trendingPosts.map((p: { id: number; slug: string; title: string; published_at?: string }) => ({
          id: p.id,
          slug: p.slug,
          title: p.title,
          timeAgo: getTimeAgo(p.published_at),
        }))
      : defaultTrendingArticles;
  const sectionTitle = latestContent?.content?.title || "Latest Articles";
  const sectionCtaLabel = latestContent?.content?.subtitle || "View all";
  const digestTitle = digestContent?.content?.title || "AI Daily Digest";
  const digestDescription = digestContent?.content?.description || "Key takeaways generated by our model from 50+ sources today.";
  const trendingTitle = trendingContent?.content?.title || "Trending Now";

  // First Ad - Paid Ads/Banner
  const adTitle = adContent?.content?.title || "My Blogs Web";
  const adDescription = adContent?.content?.description || "My Blogs Web is a blog about everything. It is a place where I share my thoughts, ideas, and experiences.";
  const adCtaLabel = adContent?.content?.subtitle || "Visit Now";
  const adLink = adContent?.content?.link || "#";
  
  // Second Ad - Visiting/Affiliate
  const ad2Title = ad2Content?.content?.title || "My Blogs Web";
  const ad2Description = ad2Content?.content?.description || "My Blogs Web is a blog about everything. It is a place where I share my thoughts, ideas, and experiences.";
  const ad2CtaLabel = ad2Content?.content?.subtitle || "Get Started";
  const ad2Link = ad2Content?.content?.link || "#";
  
  // Third Ad - Page Boosting/Contact for Ads
  const ad3Title = ad3Content?.content?.title || "Boost Your Visibility";
  const ad3Description = ad3Content?.content?.description || "Reach thousands of readers. Contact us to advertise on our platform.";
  const ad3CtaLabel = ad3Content?.content?.subtitle || "Contact Us";
  const ad3Link = ad3Content?.content?.link || "#";

  const firstRow = latestPosts.slice(0, 2);
  const secondRow = latestPosts.slice(2, 4);

  return (
    <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content - Left Column */}
        <div className="lg:col-span-2">
          {/* Section Header */}
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-2xl md:text-3xl font-bold text-black">
              {sectionTitle}
            </h2>{/* Section title */}
            <Link
              href="/blog"
              className="flex items-center gap-1 text-sm font-medium text-primary hover:gap-2 transition-all"
            >
              {sectionCtaLabel}
              <ArrowRight size={16} />
            </Link>
          </div>

          {/* Articles Grid */}
          <div className="space-y-8">
            {/* First Row - Two Articles (from server) */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {firstRow.map((post) => (
                <PostCard
                  key={post.id}
                  variant="front"
                  slug={post.slug}
                  title={post.title}
                  excerpt={post.excerpt ?? undefined}
                  category={post.category?.name ?? undefined}
                  readTime={formatReadTime(post.read_time)}
                  image={post.featured_image_url ?? undefined}
                />
              ))}
            </div>
            {firstRow.length === 0 && (
              <p className="text-center text-slate-500 py-6">No articles yet. Check back soon.</p>
            )}

            {/* AI Daily Digest Section */}
            <div className="bg-purple-50 rounded-xl p-6 md:p-8 shadow-sm border border-purple-100">
              <div className="flex items-start gap-4">
                {/* Icon */}
                <div className="shrink-0 w-12 h-12 rounded-lg bg-purple-500 flex items-center justify-center">
                  <svg
                    className="w-6 h-6 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                    />
                  </svg>
                </div>

                {/* Content */}
                <div className="flex-1">
                  <h3 className="text-xl font-bold text-slate-900 mb-2">
                    {digestTitle}
                  </h3>{/* Digest title */}
                  <p className="text-sm text-slate-600 mb-4">
                    {digestDescription}
                  </p>{/* Digest description */}

                  {/* Bullet Points */}
                  <ul className="space-y-2">
                    {trendingArticles.slice(0, 3).map((item) => (
                      <li
                        key={item.id}
                        className="flex items-start gap-2 text-sm text-slate-700"
                      >
                        <span className="text-purple-500 mt-1">•</span>
                        <span>{item.title}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>

            {/* Second Row - Two Articles (from server) */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {secondRow.map((post) => (
                <PostCard
                  key={post.id}
                  variant="front"
                  slug={post.slug}
                  title={post.title}
                  excerpt={post.excerpt ?? undefined}
                  category={post.category?.name ?? undefined}
                  readTime={formatReadTime(post.read_time)}
                  image={post.featured_image_url ?? undefined}
                />
              ))}
            </div>
            {secondRow.length === 0 && firstRow.length > 0 && (
              <p className="text-center text-slate-500 py-4">More articles on the blog.</p>
            )}

            {/* Load More Button */}
            <div className="flex justify-center pt-4">
              <Link
                href="/blog"
                className="px-6 py-3 border border-slate-300 rounded-lg font-medium text-slate-700 hover:bg-slate-50 transition-colors"
              >
                Load More Articles
              </Link>
            </div>
          </div>
        </div>

        {/* Sidebar - Right Column */}
        <div className="space-y-6">
          {/* Trending Now */}
          <div className="bg-white rounded-xl p-6 border border-slate-200 shadow-sm">
            <div className="flex items-center gap-2 mb-4">
              <TrendingUp className="w-5 h-5 text-primary" />
              <h3 className="text-lg font-bold text-slate-900">
                {trendingTitle}
              </h3>{/* Trending title */}
            </div>

            <ol className="space-y-4">
              {trendingArticles.map((article, index) => (
                <li key={article.id}>
                  <Link
                    href={`/blog/${article.slug}`}
                    className="flex items-start gap-3 group"
                  >
                    <span className="shrink-0 w-6 h-6 rounded-full bg-blue-100 text-blue-600 text-xs font-semibold flex items-center justify-center mt-0.5">
                      {index + 1}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-slate-700 group-hover:text-primary transition-colors line-clamp-2">
                        {article.title}
                      </p>
                      <p className="text-xs text-slate-500 mt-1 flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        {article.timeAgo}
                      </p>
                    </div>
                  </Link>
                </li>
              ))}
            </ol>
          </div>

          {/* First Advertisement - Paid Ads/Banner */}
          <div className="relative bg-linear-to-br from-blue-900 to-indigo-900 rounded-xl p-6 border-2 border-white/20 overflow-hidden">
            {/* Advertisement Label */}
            <div className="absolute top-3 left-3">
              <span className="text-xs font-semibold text-white/70 uppercase tracking-wide">
                Advertisement
              </span>
            </div>

            {/* Pattern Overlay */}
            <div className="absolute inset-0 opacity-10">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white rounded-full blur-3xl" />
              <div className="absolute bottom-0 left-0 w-24 h-24 bg-white rounded-full blur-2xl" />
            </div>

            {/* Content */}
            <div className="relative z-10 pt-6">
              <h3 className="text-xl font-bold text-white mb-2">
                {adTitle}
              </h3>{/* Ad title */}
              <p className="text-sm text-slate-300 mb-4">
                {adDescription}
              </p>{/* Ad description */}
              <Link
                href={adLink}
                className="inline-block px-4 py-2 bg-white text-blue-900 rounded-lg font-semibold text-sm hover:bg-slate-100 transition-colors"
              >
                {adCtaLabel}
              </Link>
            </div>
          </div>

          {/* Second Advertisement - Visiting/Affiliate */}
          <div className="relative bg-linear-to-br from-emerald-900 to-teal-900 rounded-xl p-6 border-2 border-white/20 overflow-hidden">
            {/* Advertisement Label */}
            <div className="absolute top-3 left-3">
              <span className="text-xs font-semibold text-white/70 uppercase tracking-wide">
                Advertisement
              </span>
            </div>

            {/* Pattern Overlay */}
            <div className="absolute inset-0 opacity-10">
              <div className="absolute top-0 right-0 w-28 h-28 bg-white rounded-full blur-3xl" />
              <div className="absolute bottom-0 left-0 w-20 h-20 bg-white rounded-full blur-2xl" />
            </div>

            {/* Content */}
            <div className="relative z-10 pt-6">
              <h3 className="text-xl font-bold text-white mb-2">
                {ad2Title}
              </h3>{/* Ad 2 title */}
              <p className="text-sm text-slate-300 mb-4">
                {ad2Description}
              </p>{/* Ad 2 description */}
              <Link
                href={ad2Link}
                className="inline-block px-4 py-2 bg-white text-emerald-900 rounded-lg font-semibold text-sm hover:bg-slate-100 transition-colors"
              >
                {ad2CtaLabel}
              </Link>
            </div>
          </div>

          {/* Third Advertisement - Page Boosting/Contact for Ads */}
          <div className="relative bg-linear-to-br from-purple-900 to-pink-900 rounded-xl p-6 border-2 border-white/20 overflow-hidden">
            {/* Advertisement Label */}
            <div className="absolute top-3 left-3">
              <span className="text-xs font-semibold text-white/70 uppercase tracking-wide">
                Advertisement
              </span>
            </div>

            {/* Pattern Overlay */}
            <div className="absolute inset-0 opacity-10">
              <div className="absolute top-0 right-0 w-28 h-28 bg-white rounded-full blur-3xl" />
              <div className="absolute bottom-0 left-0 w-20 h-20 bg-white rounded-full blur-2xl" />
            </div>

            {/* Content */}
            <div className="relative z-10 pt-6">
              <h3 className="text-xl font-bold text-white mb-2">
                {ad3Title}
              </h3>{/* Ad 3 title */}
              <p className="text-sm text-slate-300 mb-4">
                {ad3Description}
              </p>{/* Ad 3 description */}
              <Link
                href={ad3Link}
                className="inline-block px-4 py-2 bg-white text-purple-900 rounded-lg font-semibold text-sm hover:bg-slate-100 transition-colors"
              >
                {ad3CtaLabel}
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
